default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { postgres } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { postgres } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { postgres } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
